---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - set -e
  - if [ "${TRAVIS_TAG?}" ]; then
      AWS_BUCKET="doi.datacite.org";
      cp .env.production .env;
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="doi.test.datacite.org";
      cp .env.stage .env;
    fi
  - npm config set spin false
  - npm install -g codeclimate-test-reporter
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  # - COVERAGE=true yarn test
  # - codeclimate-test-reporter < coverage/lcov.info

  - if [ "$TRAVIS_BRANCH" != "master" ]; then
      exit 1;
    fi
  - ember build --environment=production

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  cache_control: "no-cache"
  on:
    branch: $TRAVIS_BRANCH
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
