---
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="doi.datacite.org";
      cp .env.production .env;
    else
      AWS_BUCKET="doi.test.datacite.org";
      cp .env.stage .env;
    fi
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  # - ember test
  - DEBUG=broccoli*,ember-cli* travis_wait 30 ember build --environment=production

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  cache_control: "no-cache"
  on:
    branch: $TRAVIS_BRANCH
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
