---
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
  - test

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="bracco.datacite.org";
      NPM_ENV="production";
      cp .env.production .env;
    else
      AWS_BUCKET="bracco.test.datacite.org";
      NPM_ENV="stage";
      cp .env.stage .env;
    fi
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - ember build --environment=${NPM_ENV}

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  cache_control: "max-age=31536000"
  on:
    branch: test
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
