---
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="eventdata.datacite.org";
      NPM_ENV="production";
      SITE_TITLE="DataCite Event Data";
      SEARCH_URL="https://search.datacite.org";
      CDN_HOST="assets.datacite.org";
      JWT_HOST="https://profiles.datacite.org";
    else
      AWS_BUCKET="eventdata.test.datacite.org";
      NPM_ENV="stage";
      SITE_TITLE="DataCite Event Data Test";
      NAVMENU_TITLE="Test Services";
      SEARCH_URL="https://search.test.datacite.org";
      CDN_HOST="assets.test.datacite.org";
      JWT_HOST="https://profiles.test.datacite.org";
    fi
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - ember build --environment=${NPM_ENV}

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  cache_control: "max-age=31536000"
  on:
    all_branches: true
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
