version: '2'

services:
  web:
    env_file: .env
    environment:
      - DEPLOY_TARGET=staging
    image: datacite/bracco
    build: .
    ports:
      - "9030:80"
    volumes:
      - ./public:/home/app/webapp/public
      - ./dist:/home/app/webapp/dist
      - ./vendor:/home/app/webapp/vendor
